"""changed category to department

Revision ID: 4de5f3d83c8c
Revises: 7c08a0334368
Create Date: 2018-12-28 17:48:13.012756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de5f3d83c8c'
down_revision = '7c08a0334368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
